### ISSUE TITLE
Who is Tonya Beige?  (and not John Gault)...

### ISSUE THREAD

**Issue by BBC-Esq** [collabora/WhisperSpeech#119]
I'm seeing some shiny new models on huggingface, including a "fast" version of "small" and other stuff...Was just curious what the differences are and if there's going to be some explanation in the readme or somewhere?  The commit notes say "Tonya Beige" and stuff like that.  lol.

**Comment by jpc** [comment]
Hehe, the names come from `faker` a Python library generating random but readable names. I am afraid there are no mysterious ex-girlfriends as someone suggested on Discord ;)

The new models are trained with a reversed balance between encoder and decoder layers (so 3/4th of layers in the encoder). This makes them significantly faster when generating speech and also more robust. Unfortunately they also take 10x longer to train...

I need to start updating the README since there are new docs scattered around the place, fine-tuning scripts are also almost ready...
