### ISSUE TITLE
The sequence length when training semantic token to acoustic token

### ISSUE THREAD

**Issue by yangdongchao** [collabora/WhisperSpeech#17]
Hi, I want to ask the sequence length when you train your S2A model. Because SpearTTS directly predict 3 codebook's tokens. We found that if the target audio is more than 10s, the total sequence length will be very long, and the transformer model is hard to model the long sequence.
Furthermore, whether you considering to use better codec model? We have train some codec model on TTS data, I belive it can improve the performance of this project. We have train codec on 16khz, which may more easy to train. We have release part of code on https://github.com/yangdongchao/AcademiCodec
If you are interested in this, please let me know, I am willing to help you provide better codec model. I want to finish this amazing project together!

**Comment by jpc** [comment]
Hey, thanks for reaching out. I've seen your AcademiCodec repo, great work! 👍 I'd love to work together with you to Open Source TTS forward faster.

The current S2A model is working from 1500 semantic tokens to 4500 acoustic tokens (1.5kbps, 2 quantizers). I've extended it to 9000 tokens (3kbps, 4 quantizers) and the training took just 2x longer. I suspect it's because of the new PyTorch 2.0 optimized attention implementation that manages to hide the O(N^2) scaling I would expect.

Unfortunately the quality from the 3kbps multi-purpose EnCodec model is not great and the 3kbps S2A model trained for the same amount of epochs makes more mistakes.

I am now looking at training a separate model that would take the synthesized codes for 2 quantizers (1.5kbps) and "upsample" it to 8 quantizers (6kbps). The https://github.com/suno-ai/bark project validated this idea and I already managed to train a simple 2->4 "upsampling" model with great results.

**Comment by yangdongchao** [comment]
> Hey, thanks for reaching out. I've seen your AcademiCodec repo, great work! 👍 I'd love to work together with you to Open Source TTS forward faster.
> 
> The current S2A model is working from 1500 semantic tokens to 4500 acoustic tokens (1.5kbps, 2 quantizers). I've extended it to 9000 tokens (3kbps, 4 quantizers) and the training took just 2x longer. I suspect it's because of the new PyTorch 2.0 optimized attention implementation that manages to hide the O(N^2) scaling I would expect.
> 
> Unfortunately the quality from the 3kbps multi-purpose EnCodec model is not great and the 3kbps S2A model trained for the same amount of epochs makes more mistakes.
> 
> I am now looking at training a separate model that would take the synthesized codes for 2 quantizers (1.5kbps) and "upsample" it to 8 quantizers (6kbps). The https://github.com/suno-ai/bark project validated this idea and I already managed to train a simple 2->4 "upsampling" model with great results.

Thanks for your reply.  I think your plan is very nice. I believe my audio codec model can help to improve this project. I can help you to train a audio codec works on 16khz and 320 down-sample (1 second audio will produce 50 tokens per quantizer), which means that you can train a S2A model using 1500 semantic tokens to 4500 acoustic tokens (3 quantizers, the same process with Google). We test using 3 quantizers can get good reconstruction performance.  We can discuss how to better communication with each other, so that we can push the project together.

**Comment by jpc** [comment]
In our internal tests AcademiCodec did provide the best quality (followed closely by Descript DAC).
Independently the Vocos vocoder was released and it proved more convenient for us since it could reuse the existing Encodec tokens and still deliver great speech quality.
